name: PlatformIO CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e m5stick-c
    - name: Move files
      run: |
        mkdir files
        mv .pio/build/m5stick-c/firmware.bin files/firmware.bin
    - name: Create version file
      run: echo ${GITHUB_REF#refs/*/} > files/version.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "files/firmware.bin,files/version.txt"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "files/"
        dist_target_dir: "/"